# -*- coding: utf-8 -*-

# Scanenr mapping
from collections import defaultdict

# d=TrueManufacturerModelName
# name='sdfsd,SOMATOM Definition Flash'
# searchKey(d, name)

def searchKey(d, name):
    model=''
    for k in d.keys():
        if k.lower() in name.lower():
            model = d[k]
    return model

# Define CertifiedManufacturerModelName
CertifiedManufacturerModelNameCTDict = defaultdict(lambda: '', {
    'P01': 'Aquilion ONE',
    'P02': 'SOMATOM Definition Flash',
    'P04': 'Aquilion ONE',
    'P05': 'Aquilion ONE',
    'P06': 'SOMATOM Definition AS plus',
    'P07': 'SOMATOM Definition Flash',
    'P08': 'Brilliance iCT',
    'P09': 'Brilliance 64',
    'P10': 'Discovery CT750 HD',
    'P11': 'SOMATOM Definition Flash',
    'P12': 'Definition DS dual-source',
    'P13': 'Optima',
    'P14': 'Aquilion ONE',
    'P15': 'SOMATOM Definition Flashh',
    'P16': 'SOMATOM Force',
    'P17': 'SOMATOM Definition AS plus',
    'P18': 'SOMATOM Definition Flash',
    'P19': 'SOMATOM Definition AS plus',
    'P22': 'Aquilion ONE',
    'P23': 'Aquilion Premium 160',
    'P29': 'Discovery PET-CT',
    'P30': 'Definition Force',
    'P31': 'SOMATOM Sensation 64',
    'P32': 'Aquilion CXL 128',
    'P33': 'SOMATOM Definition AS plus',
    'P36': 'SOMATOM Definition Flash'})

# Define CertifiedManufacturer
CertifiedManufacturerCTDict = defaultdict(lambda: '', {
    'P01': 'TOSHIBA',
    'P02': 'Siemens',
    'P04': 'TOSHIBA',
    'P05': 'TOSHIBA',
    'P06': 'Siemens',
    'P07': 'Siemens',
    'P08': 'Philips',
    'P09': 'Philips',
    'P10': 'GE',
    'P11': 'Siemens',
    'P12': 'Siemens',
    'P13': 'GE',
    'P14': 'TOSHIBA',
    'P15': 'Siemens',
    'P16': 'Siemens',
    'P17': 'Siemens',
    'P18': 'Siemens',
    'P19': 'Philips',
    'P22': 'TOSHIBAE',
    'P23': 'TOSHIBA',
    'P29': 'GE',
    'P30': 'Siemens',
    'P31': 'Siemensn',
    'P32': 'TOSHIBA',
    'P33': 'Siemenss',
    'P36': 'Siemens'})

# Define TrueManufacturerModelName
TrueManufacturerModelNameCTDict = defaultdict(lambda: '', {
    'SOMATOM Definition': 'SOMATOM Definition',
    'Aquilion ONE': 'Aquilion ONE',
    'AXIOM-Artis': 'AXIOM Artis',
    'Centricity Radiology RA 600': 'Centricity Radiology RA 600',
    'Aquilion PRIME': 'Aquilion PRIME',
    'INFINIA': 'INFINIA',
    'Centricity Cardiology CA 1000': 'Centricity Cardiology CA 1000',
    'SOMATOM Definition Flash': 'SOMATOM Definition Flash',
    'SOMATOM Definition AS+': 'SOMATOM Definition AS plus',
    'AlluraXper': 'Centricity Cardiology CA',
    'DFP-8000D': 'DFP-8000D',
    'Symbia Intevo Excel': 'Symbia Intevo Excel',
    'INTEGRIS V': 'INTEGRIS V',
    'INTEGRIS Allura Flat Detector': 'INTEGRIS Allura Flat Detector',
    'BrightView': 'BrightView',
    'iCT 256': 'Brilliance iCT',
    'Brilliance 64': 'Brilliance 64',
    'LightSpeed VCT': 'LightSpeed VCT',
    'Discovery* PET/CT 710': 'Discovery* PET/CT 710',
    'Symbia Intevo': 'Symbia Intevo',
    'ACUSON SC2000': 'ACUSON SC2000',
    'ACUSON SC2000': 'ACUSON SC2000',
    'SOMATOM Emotion': 'SOMATOM Emotion',
    'HD15': ' HD15',
    'Achieva': 'Diamond Select Achieva',
    'EPIQ 7G': 'EPIQ 7G',
    'IQon Spectral CT': 'IQon Spectral CT',
    'CardioGraphe': 'CardioGraphe',
    'Discovery CT750 HD': 'Discovery CT750 HD',
    'Azurion': 'Azurion',
    's5': 'Volcano s5',
    'EPIQ 7C': 'EPIQ 7C',
    'Signa HDxt': 'Signa HDxt',
    'Allura Clarity': 'AlluraClarity',
    'Optima CT660': 'Optima CT660',
    'iE33': 'iE33',
    'Sensation 64': 'SOMATOM Sensation 64',
    'SOMATOM Force': 'SOMATOM Force',
    'Sensation 16': 'SOMATOM Sensation 16',
    'Aquilion': 'Aquilion ONE',
    'SOMATOM Drive': 'SOMATOM Drive',
    'Discovery 690': 'Discovery PET/CT 690',
    'Vivid7': 'Vivid 7'})

# Define TrueManufacturer
TrueManufacturerCTDict = defaultdict(lambda: '', {
    'TOSHIBA': 'TOSHIBA',
    'Siemens': 'Siemens',
    'Philips Medical Systems': 'Philips',
    'Philips Healthcare': 'Philips',
    'Philips': 'Philips',
    'GE MEDICAL SYSTEMS': 'GE',
    'SIEMENS': 'Siemens',
    'GE Vingmed Ultrasound': 'GE'})


##############################################################


# Define CertifiedManufacturerModelName
CertifiedManufacturerModelNameICADict = defaultdict(lambda: '', {
    'P01': 'Axiom Artis',
    'P02': 'INNOVA 2100 IQ',
    'P04': 'ALLURA Xper FD20',
    'P05': 'Alura FD10, Cath3/5',
    'P06': 'Allura Xper FD 10',
    'P07': 'Allura Xper FD 10/10',
    'P08': 'INNOVA 2100 IQ',
    'P09': 'Innova 310',
    'P10': 'ANOVA coronary fluoroscopy suite',
    'P11': 'ALLURA',
    'P12': 'ALLURE 5000',
    'P13': 'Innova 2100 IQ',
    'P14': 'INNOVA 4100 SE MEDICAL SYSTEM 2007',
    'P15': 'Innova 3100',
    'P16': 'Action-Artis',
    'P17': 'Artis Zee Floor',
    'P18': 'Axiom Artis',
    'P19': 'Axiom Artis',
    'P22': 'Innova 2100',
    'P23': 'Allura Clarity Cardiovascular Cath Lab',
    'P29': 'Artis Zee ',
    'P30': '',
    'P31': '',
    'P32': 'Axiom Artis dFA',
    'P33': 'Coroskop',
    'P36': ''})

# Define CertifiedManufacturer
CertifiedManufacturerICADict = defaultdict(lambda: '', {
    'P01': 'Siemens',
    'P02': 'Siemens',
    'P04': 'GE',
    'P05': 'Philips',
    'P06': 'Philips',
    'P07': 'Philips',
    'P08': 'GE',
    'P09': 'GE',
    'P10': 'GE',
    'P11': 'Philips',
    'P12': 'Philips',
    'P13': 'GE',
    'P14': 'GE',
    'P15': 'GE',
    'P16': 'Siemens',
    'P17': 'Siemens',
    'P18': 'Siemens',
    'P19': 'Siemens',
    'P22': 'GE',
    'P23': 'Philips',
    'P29': 'Siemens',
    'P30': '',
    'P31': '',
    'P32': 'Siemens',
    'P33': 'Siemens',
    'P36': ''})

# Define TrueManufacturerModelName
TrueManufacturerModelNameICADict = defaultdict(lambda: '', {
    'SOMATOM Definition': 'SOMATOM Definition',
    'Aquilion ONE': 'Aquilion ONE',
    'AXIOM-Artis': 'AXIOM Artis',
    'Centricity Radiology RA 600': 'Centricity Radiology RA 600',
    'Aquilion PRIME': 'Aquilion PRIME',
    'INFINIA': 'INFINIA',
    'Centricity Cardiology CA 1000': 'Centricity Cardiology CA 1000',
    'SOMATOM Definition Flash': 'SOMATOM Definition Flash',
    'SOMATOM Definition AS+': 'SOMATOM Definition AS plus',
    'AlluraXper': 'Centricity Cardiology CA',
    'DFP-8000D': 'DFP-8000D',
    'Symbia Intevo Excel': 'Symbia Intevo Excel',
    'INTEGRIS V': 'INTEGRIS V',
    'INTEGRIS Allura Flat Detector': 'INTEGRIS Allura Flat Detector',
    'BrightView': 'BrightView',
    'iCT 256': 'Brilliance iCT',
    'Brilliance 64': 'Brilliance 64',
    'LightSpeed VCT': 'LightSpeed VCT',
    'Discovery* PET/CT 710': 'Discovery* PET/CT 710',
    'Symbia Intevo': 'Symbia Intevo',
    'ACUSON SC2000': 'ACUSON SC2000',
    'ACUSON SC2000': 'ACUSON SC2000',
    'SOMATOM Emotion': 'SOMATOM Emotion',
    'HD15': ' HD15',
    'Achieva': 'Diamond Select Achieva',
    'EPIQ 7G': 'EPIQ 7G',
    'IQon Spectral CT': 'IQon Spectral CT',
    'CardioGraphe': 'CardioGraphe',
    'Discovery CT750 HD': 'Discovery CT750 HD',
    'Azurion': 'Azurion',
    's5': 'Volcano s5',
    'EPIQ 7C': 'EPIQ 7C',
    'Signa HDxt': 'Signa HDxt',
    'Allura Clarity': 'AlluraClarity',
    'Optima CT660': 'Optima CT660',
    'iE33': 'iE33',
    'Sensation 64': 'SOMATOM Sensation 64',
    'SOMATOM Force': 'SOMATOM Force',
    'Sensation 16': 'SOMATOM Sensation 16',
    'Aquilion': 'Aquilion ONE',
    'SOMATOM Drive': 'SOMATOM Drive',
    'Discovery 690': 'Discovery PET/CT 690',
    'Vivid7': 'Vivid 7',
    'Vivid7': 'Vivid 7'})

# Define TrueManufacturer
TrueManufacturerICADict = defaultdict(lambda: '', {
    'TOSHIBA': 'TOSHIBA',
    'Siemens': 'Siemens',
    'Philips Medical Systems': 'Philips',
    'Philips Healthcare': 'Philips',
    'Philips': 'Philips',
    'GE MEDICAL SYSTEMS': 'GE',
    'SIEMENS': 'Siemens',
    'GE Vingmed Ultrasound': 'GE'})

##############################################################

# CT-Scanner, ICA-Equipment, Ultrasonic-System, MR-System, OTHER
ScannerType = defaultdict(lambda: '', {
    'SOMATOM Definition': 'CT-Scanner',
    'Aquilion ONE': 'CT-Scanner',
    'AXIOM Artis': 'CT-Scanner',
    'Centricity Radiology RA 600': 'OTHER',
    'Aquilion PRIME': 'CT-Scanner',
    'INFINIA': 'CT-Scanner',
    'Centricity Cardiology CA 1000': 'OTHER',
    'SOMATOM Definition Flash': 'CT-Scanner',
    'SOMATOM Definition AS plus': 'CT-Scanner',
    'Centricity Cardiology CA': 'OTHER',
    'DFP-8000D': 'CT-Scanner',
    'Symbia Intevo Excel': 'CT-Scanner',
    'INTEGRIS V': 'CT-Scanner',
    'INTEGRIS Allura Flat Detector': 'CT-Scanner',
    'BrightView': 'CT-Scanner',
    'Brilliance iCT': 'CT-Scanner',
    'Brilliance 64': 'CT-Scanner',
    'LightSpeed VCT': 'CT-Scanner',
    'Discovery* PET/CT 710': 'CT-Scanner',
    'Symbia Intevo': 'CT-Scanner',
    'ACUSON SC2000': 'Ultrasonic-System',
    'ACUSON SC2000': 'Ultrasonic-System',
    'SOMATOM Emotion': 'CT-Scanner',
    'HD15': ' Ultrasonic-System',
    'Diamond Select Achieva': 'MR-Systema',
    'EPIQ 7G': 'Ultrasonic-System',
    'IQon Spectral CT': 'CT-Scanner',
    'CardioGraphe': 'CT-Scanner',
    'Discovery CT750 HD': 'CT-Scanner',
    'Azurion': 'CT-Scanner',
    'Volcano s5': 'Ultrasonic-System',
    'EPIQ 7C': 'Ultrasonic-System',
    'Signa HDxt': 'MR-System',
    'AlluraClarityy': 'CT-Scanner',
    'Optima CT660': 'CT-Scanner',
    'iE33': 'Ultrasonic-System',
    'SOMATOM Sensation 64': 'CT-Scanner',
    'SOMATOM Force': 'CT-Scanner',
    'SOMATOM Sensation 16': 'CT-Scanner',
    'SOMATOM Drive': 'CT-Scanner',
    'Discovery PET/CT 690': 'CT-Scanner',
    'Vivid 7': 'Ultrasonic-System'})